"""
Repolect — Configuration System
Persistent YAML config at ~/.repolect/config.yaml (global)
with optional per-repo .repolect/config.yaml override.
 
Written by install.sh, read by all Repolect components.
"""
 
from __future__ import annotations
 
import logging
import os
from pathlib import Path
from typing import Any
 
logger = logging.getLogger(__name__)
 
# ── Paths ────────────────────────────────────────────────────────────────────
 
GLOBAL_CONFIG_DIR = Path.home() / ".repolect"
GLOBAL_CONFIG_FILE = GLOBAL_CONFIG_DIR / "config.yaml"
LOCAL_CONFIG_NAME = "config.yaml"  # inside .repolect/
 
# ── Defaults ─────────────────────────────────────────────────────────────────
 
DEFAULT_CONFIG: dict[str, Any] = {
    "mode": "local",                          # "local" or "custom"
 
    # LLM provider
    "provider": "ollama",                     # "ollama" or "openai-compatible"
    "base_url": "http://localhost:11434",      # Ollama default
    "model_name": "qwen3.5:4b",
    "api_key": "",                            # empty for Ollama
 
    # LLM call defaults
    "temperature": "0.1",
    "max_tokens": "200",
    "timeout": "60",                          # request timeout in seconds
 
    # Embeddings
    "embedding_provider": "ollama",           # "ollama" or "openai-compatible"
    "embedding_model": "qwen3-embedding:0.6b",
    "embedding_base_url": "",                 # empty = same as provider base_url
}
 
# Env var overrides — maps config keys to env var names
_ENV_OVERRIDES: dict[str, str] = {
    "provider": "REPOLECT_PROVIDER",
    "base_url": "REPOLECT_BASE_URL",
    "model_name": "REPOLECT_MODEL",
    "api_key": "REPOLECT_API_KEY",
    "temperature": "REPOLECT_TEMPERATURE",
    "max_tokens": "REPOLECT_MAX_TOKENS",
    "timeout": "REPOLECT_TIMEOUT",
    "embedding_provider": "REPOLECT_EMBED_PROVIDER",
    "embedding_model": "REPOLECT_EMBED_MODEL",
    "embedding_base_url": "REPOLECT_EMBED_BASE_URL",
}
 
 
# ── YAML I/O (inline, no PyYAML dependency) ─────────────────────────────────
 
def _parse_yaml(text: str) -> dict[str, str]:
    """Minimal YAML parser for flat key: value files. No nested structures."""
    result: dict[str, str] = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        key = key.strip()
        value = value.strip()
        # Strip optional quotes
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
            value = value[1:-1]
        result[key] = value
    return result
 
 
def _dump_yaml(config: dict[str, Any]) -> str:
    """Minimal YAML dumper for flat key: value dicts."""
    lines = ["# Repolect configuration", "# Generated by install.sh or repolect config", ""]
    for key, value in config.items():
        if isinstance(value, str) and (not value or " " in value or ":" in value):
            lines.append(f'{key}: "{value}"')
        else:
            lines.append(f"{key}: {value}")
    lines.append("")
    return "\n".join(lines)
 
 
# ── Public API ───────────────────────────────────────────────────────────────
 
def load_config(repo_root: str | Path | None = None) -> dict[str, Any]:
    """Load config with merge order: defaults → global → per-repo → env vars.
 
    Args:
        repo_root: Optional repo root for per-repo config override.
 
    Returns:
        Merged config dict.
    """
    config = dict(DEFAULT_CONFIG)
 
    # Layer 1: Global config
    if GLOBAL_CONFIG_FILE.exists():
        try:
            text = GLOBAL_CONFIG_FILE.read_text(encoding="utf-8")
            global_cfg = _parse_yaml(text)
            config.update({k: v for k, v in global_cfg.items() if v})
            logger.debug("Loaded global config from %s", GLOBAL_CONFIG_FILE)
        except Exception as e:
            logger.warning("Failed to read global config: %s", e)
 
    # Layer 2: Per-repo config (overrides global)
    if repo_root:
        local_path = Path(repo_root) / ".repolect" / LOCAL_CONFIG_NAME
        if local_path.exists():
            try:
                text = local_path.read_text(encoding="utf-8")
                local_cfg = _parse_yaml(text)
                config.update({k: v for k, v in local_cfg.items() if v})
                logger.debug("Loaded per-repo config from %s", local_path)
            except Exception as e:
                logger.warning("Failed to read per-repo config: %s", e)
 
    # Layer 3: Environment variable overrides (highest priority)
    for config_key, env_var in _ENV_OVERRIDES.items():
        env_val = os.environ.get(env_var, "").strip()
        if env_val:
            config[config_key] = env_val
 
    return config
 
 
def save_config(config: dict[str, Any], global_only: bool = True,
                repo_root: str | Path | None = None) -> Path:
    """Save config to YAML file.
 
    Args:
        config: Config dict to save.
        global_only: If True, write to ~/.repolect/config.yaml.
                     If False, write to repo's .repolect/config.yaml.
        repo_root: Required if global_only is False.
 
    Returns:
        Path to the written config file.
    """
    if global_only:
        target = GLOBAL_CONFIG_FILE
        GLOBAL_CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    else:
        if not repo_root:
            raise ValueError("repo_root required for per-repo config")
        target = Path(repo_root) / ".repolect" / LOCAL_CONFIG_NAME
        target.parent.mkdir(parents=True, exist_ok=True)
 
    target.write_text(_dump_yaml(config), encoding="utf-8")
    logger.info("Config saved to %s", target)
    return target
 
 
def get_config_value(key: str, default: Any = None,
                     repo_root: str | Path | None = None) -> Any:
    """Get a single config value with full merge + env override."""
    config = load_config(repo_root)
    return config.get(key, default)
 
 
def config_exists() -> bool:
    """Check if a global config file exists."""
    return GLOBAL_CONFIG_FILE.exists()
 